# Uncomment the next line to define a global platform for your project
platform :osx, ’10.12’

target 'SequenceManager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SWXMLHash', '~> 4.0.0'
  # Pods for SequenceManager

  target 'SequenceManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SequenceManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
